version: '3'

services:
  # nest-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-app
  #   working_dir: /app
  #   volumes:
  #     - ./src:/app/src
  #     - ./node_modules:/app/node_modules
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mysql

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    depends_on:
      - mysql

volumes:
  mysql_data:

